version: "3.7"

services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    restart: always  
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - /var/log:/var/log
    networks:
      - monitoring_network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    restart: always  
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id:ro
    networks:
      - monitoring_network
    restart: unless-stopped

networks:
  monitoring_network:
    external: true

