server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "system"
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/*log
          
  - job_name: "journal"
    journal:
      max_age: 12h
      labels:
        job: journal
    pipeline_stages:
      - docker: {}

