---
- name: Disk Usage Check
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Run disk usage command
      shell: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout }}"
