---
- name: Check DNS resolution
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    domain_to_check: "example.com"

  tasks:
    - name: Resolve domain
      shell: "nslookup {{ domain_to_check }}"
      register: dns_result
      ignore_errors: yes

    - name: Show DNS resolution result
      debug:
        msg: "{{ dns_result.stdout }}"
