- name: Cleanup disk space
  hosts: all
  become: yes
  tasks:
    - name: Remove old logs
      shell: find /var/log -type f -name "*.log" -mtime +7 -delete

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes
