version: '3.8'

networks:
  monitoring_network:
    external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    restart: always  
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - monitoring_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    container_name: logstash
    restart: always  
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044" # Filebeat input
    networks:
      - monitoring_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    restart: always  
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - monitoring_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    restart: always  
    user: root
    depends_on:
      - logstash
    volumes:
      - /var/log:/var/log:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - monitoring_network

volumes:
  elasticsearch_data:

